name: gh-acr-AI0030
on: 
  push:
    branches: main
    paths: AI0030/**
  workflow_dispatch:
jobs:
  gh-acr-build-push:
    runs-on: ubuntu-latest 
    steps:
    - name: 'checkout action'
      uses: actions/checkout@main
    
    - name: 'azure login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run:  |
        docker build ./AI0030/ModelMonitoring -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/modelmonitoring:AI0030
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/modelmonitoring:AI0030
        docker build ./AI0030/DataIngestion -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/dataingestion:AI0030
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/dataingestion:AI0030		
        docker build ./AI0030/DataTransformation -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/datatransformation:AI0030
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/datatransformation:AI0030
        docker build ./AI0030/FeatureEngineering -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/featureengineering:AI0030
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/featureengineering:AI0030
        docker build ./AI0030/ModelRegistry -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/modelregistry:AI0030
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/modelregistry:AI0030		
        docker build ./AI0030/ModelServing -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/modelserving:AI0030
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/modelserving:AI0030		
        docker build ./AI0030/ModelTraining_XGBClassifier_MLBased -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/modeltraining_xgbclassifier_mlbased:AI0030
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/modeltraining_xgbclassifier_mlbased:AI0030
