name: gh-acr-AI0032
on: 
  push:
    branches: main
    paths: AI0032/**
  workflow_dispatch:
jobs:
  gh-acr-build-push:
    runs-on: ubuntu-latest 
    steps:
    - name: 'checkout action'
      uses: actions/checkout@main
    
    - name: 'azure login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run:  |
        docker build ./AI0032/ModelMonitoring -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/modelmonitoring:AI0032
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/modelmonitoring:AI0032
        docker build ./AI0032/DataIngestion -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/dataingestion:AI0032
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/dataingestion:AI0032		
        docker build ./AI0032/DataTransformation -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/datatransformation:AI0032
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/datatransformation:AI0032
        docker build ./AI0032/FeatureEngineering -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/featureengineering:AI0032
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/featureengineering:AI0032
        docker build ./AI0032/ModelRegistry -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/modelregistry:AI0032
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/modelregistry:AI0032		
        docker build ./AI0032/ModelServing -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/modelserving:AI0032
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/modelserving:AI0032		
        docker build ./AI0032/ModelTraining_XGBRegressor_MLBased -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/modeltraining_xgbregressor_mlbased:AI0032
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/modeltraining_xgbregressor_mlbased:AI0032
